services:
  db:
    container_name: note-app-db
    env_file: .env
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DEV_POSTGRES_DB}
      POSTGRES_USER: ${DEV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DEV_POSTGRES_PASSWORD}
    ports:
      - "6000:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
